services:
  db:
    build:
      context: .
      dockerfile: containers/postgres/Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
        - .env
  app:
    build:
      context: .
      dockerfile: containers/django/Dockerfile
    # ボリュームを指定
    # ローカルのカレントディレクトリをコンテナの/codeにマウントする
    # ローカルの/staticをコンテナの/staticにマウントする
    # ローカルのapp-bashhistoryをコンテナの/root/myhistoryにマウントする
    volumes:
      - .:/code
      - app-bashhistory:/root/myhistory
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    # シェルスクリプトを実行
    command: >
      sh -c "
      python manage.py makemigrations --noinput &&
      python manage.py migrate --noinput &&
      if [ \$DEBUG = 'True' ]; then
        python manage.py runserver 0.0.0.0:8000;
      else
        gunicorn NicheMap2.wsgi:application --bind 0.0.0.0:8000;
      fi
      "
volumes:
  db_data:
  app-bashhistory: