# Generated by Django 4.2.7 on 2024-12-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_candidaterestaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidaterestaurant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
