# Generated by Django 4.2.7 on 2024-12-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_candidaterestaurant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidaterestaurant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
