# Generated by Django 4.2.7 on 2024-12-22 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_alter_candidaterestaurant_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidaterestaurant',
            old_name='name',
            new_name='display_name',
        ),
        migrations.RenameField(
            model_name='candidaterestaurant',
            old_name='image',
            new_name='photos',
        ),
    ]
