# Generated by Django 4.2.7 on 2025-01-13 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0007_rename_name_candidaterestaurant_display_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidaterestaurant',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PassedRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_type_display_name', models.CharField(choices=[('ramen_restaurant', 'ラーメン屋'), ('fast_food_restaurant', 'ファーストフード'), ('chinese_restaurant', '中華料理'), ('french_restaurant', 'フランス料理'), ('japanese_restaurant', '日本料理'), ('italian_restaurant', 'イタリア料理'), ('sushi_restaurant', '寿司屋'), ('steak_house', 'ステーキハウス'), ('bakery', 'パン屋'), ('cafe', 'カフェ'), ('bar', 'バー'), ('meal_takeaway', 'テイクアウト')], max_length=255)),
                ('candidate_restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.candidaterestaurant')),
            ],
        ),
    ]
